export const TEACHER_SPACES_COPY = {
  title: '스페이스',
  subtitle: (name: string) => `${name}님의 교육 스페이스입니다.`,
  createButtonLabel: '새 스페이스',
  createDialogTitle: '새 스페이스',
  createNameLabel: '스페이스 이름',
  createNamePlaceholder: '스페이스 이름을 입력하세요',
  createDescriptionLabel: '스페이스 설명',
  createDescriptionPlaceholder: '스페이스 설명을 입력하세요',
  createClose: '닫기',
  createSubmit: '만들기',
  createError: '스페이스 생성에 실패했습니다. 잠시 후 다시 시도해주세요.',
  problemCount: (count: number) => `${count}문항`,
  memberCount: (count: number) => `${count}명`,
  lectureCount: (count: number) => `${count}개`,
  emptyTitle: '표시할 스페이스가 없습니다',
  emptyDescription: '새 스페이스를 만들어 수업을 시작해 보세요.',
  emptyHint: '우측 상단의 새 스페이스 버튼으로 첫 스페이스를 만들 수 있습니다.',
} as const
