export const TEACHER_INVITE_STUDENTS_COPY = {
  pageTitle: '학습자 초대',
  invalidSpace: '유효한 스페이스를 찾을 수 없습니다.',
  inviteCodeTitle: '초대 코드',
  inviteCodeDescription: '아래 코드를 학습자들에게 공유하세요.',
  inviteCodeLabel: '스페이스 초대 코드',
  copyCode: '초대 코드 복사',
  copied: '복사됨',
  copyError: '클립보드에 복사하지 못했습니다.',
  emailTitle: '이메일로 초대',
  emailDescription: '학습자의 이메일 주소를 입력하여 참여 코드를 보내세요.',
  emailLabel: '이메일',
  emailPlaceholder: 'student@example.com',
  addEmail: '추가',
  sendInvite: '초대 보내기',
  sending: '전송 중…',
  sendSuccess: (count: number) => `${count}명에게 초대 이메일을 보냈습니다.`,
  sendError: '초대 이메일 전송에 실패했습니다. 이메일을 확인해 주세요.',
  emailRequired: '최소 한 개의 이메일을 추가해 주세요.',
  invalidEmail: '올바른 이메일 주소를 입력해 주세요.',
  duplicateEmail: '이미 추가된 이메일입니다.',
  removeEmail: (email: string) => `${email} 삭제`,
} as const
