export const TEACHER_SPACE_DETAIL_COPY = {
  backToSpaces: '스페이스 목록으로',
  invalidSpace: '유효한 스페이스를 찾을 수 없습니다.',
  inviteStudents: '학습자 초대',
  createProblem: '문항 생성',
  totalProblems: '총 문항',
  learners: '학습자',
  pending: '대기 중',
  feedbackComplete: '피드백 완료',
  problemManagement: '문항 관리',
  submissionStatus: '제출 현황',
  problemSubmissionStatus: '제출 현황',
  editProblem: '수정',
  feedbackPending: '대기 중',
  feedbackCompleted: '피드백 완료',
  commentCount: (count: number) => `댓글 ${count}`,
  emptyTitle: '등록된 문항이 없습니다',
  emptyDescription: '문항 생성 버튼으로 첫 문항을 추가해 보세요.',
  emptySubmissionsTitle: '제출된 과제가 없습니다',
  emptySubmissionsDescription: '학습자가 문항을 제출하면 이곳에서 확인할 수 있습니다.',
  testcaseCount: (count: number) => `테스트 케이스 ${count}개`,
  copyInviteCodeLabel: '스페이스 초대 코드를 복사합니다.',
} as const
